services:

  productdb:
    image: mcr.microsoft.com/mssql/server:2019-latest

  gatewayapi:
    image: ${DOCKER_REGISTRY-}gatewayapi
    build:
      context: .
      dockerfile: GatewayApi/Dockerfile
