services:

  productdb:
    container_name: productdb
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=MyP455w@rd!
      - MSSQL_PID=Developer
    restart: always
    ports:
      - "1433:1433"   

  productservice.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Product=Server=productdb;Database=ProductDb;User Id=sa;Password=MyP455w@rd!;TrustServerCertificate=True;
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
    depends_on:
      - productdb
    ports:
      - "8010:8080"
      - "8020:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
