services:

  productdb:
    image: mcr.microsoft.com/mssql/server:2019-latest

  productservice.api:
    image: ${DOCKER_REGISTRY-}productserviceapi
    build:
      context: .
      dockerfile: Services/Product/Product.Api/Product.Api/Dockerfile

