# Docker Http
#@Product.Api_HostAddress = http://localhost:8010

# Localhost Http
 @Product.Api_HostAddress = http://localhost:5132

# Localhost Https
# @Product.Api_HostAddress = https://localhost:7060


POST {{Product.Api_HostAddress}}/product
Accept: application/json
Content-Type: application/json
{
  "name": "Test abc11",
  "description": "descrizione 123dd",
  "price": 0,
  "categoryId": 2000
}
###

PATCH {{Product.Api_HostAddress}}/product/1
Accept: application/json
Content-Type: application/json
{
  "id": 1,
  "name": "new name!!!",
  "description": "new description!!!",
  "price": 1200
}
###

POST {{Product.Api_HostAddress}}/product/category
Accept: application/json
Content-Type: application/json
{
    "name": "Test123123"
}
###

GET {{Product.Api_HostAddress}}/product/Categories
Content-Type: application/json
###

GET  {{Product.Api_HostAddress}}/products?pageNumber=1&pageSize=100
Content-Type: application/json
###

GET {{Product.Api_HostAddress}}/product/1
Content-Type: application/json
###

  DELETE {{Product.Api_HostAddress}}/Product/125