@GatewayApi_HostAddress = http://localhost:8010

GET {{GatewayApi_HostAddress}}/products?pageNumber=1&pageSize=1
Accept: application/json

###
GET {{GatewayApi_HostAddress}}/product/1
Accept: application/json

###